# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-19 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171018_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='phone_number',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
