# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-19 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_job_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
