# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-19 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20171019_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
