# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-27 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20171026_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='state',
            field=models.CharField(max_length=20),
        ),
    ]
