# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-17 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20180717_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='contact_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='establishment_name',
            field=models.CharField(max_length=50),
        ),
    ]
