# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-17 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20180717_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='salary',
        ),
        migrations.AlterField(
            model_name='job',
            name='contact_number',
            field=models.CharField(max_length=50),
        ),
    ]
